// Turn the sliced sprites in ./sounds (<profile>.mp3 + <profile>.json, produced from
// CC0 recordings, see sounds/SOURCES.md) into the modules the engine imports:
//   src/audio/sounds/<profile>.ts  - the sprite as a base64 string (one lazy chunk each)
//   src/audio/sounds/manifest.ts   - stroke offsets per profile
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const profiles = ['blue', 'brown', 'red', 'cream'];
const manifest = {};

for (const profile of profiles) {
  const mp3 = readFileSync(join(root, 'sounds', `${profile}.mp3`));
  const meta = JSON.parse(readFileSync(join(root, 'sounds', `${profile}.json`), 'utf8'));
  manifest[profile] = { down: meta.down, up: meta.up };
  writeFileSync(
    join(root, 'src/audio/sounds', `${profile}.ts`),
    `// Generated by scripts/encode-sounds.mjs from sounds/${profile}.mp3. Do not edit.\n` +
      `// Source recordings are CC0 (public domain); see sounds/SOURCES.md.\n` +
      // Typed as string so declaration files stay tiny (no literal type).
      `const sprite: string =\n  '${mp3.toString('base64')}';\nexport default sprite;\n`,
  );
  console.log(
    `${profile}: ${(mp3.length / 1024).toFixed(1)} kB mp3, ${meta.down.length} down, ${meta.up.length} up`,
  );
}

writeFileSync(
  join(root, 'src/audio/sounds/manifest.ts'),
  `// Generated by scripts/encode-sounds.mjs. Do not edit.\n` +
    `// [startMs, durationMs] of each stroke inside the profile's sprite.\n` +
    `export const manifest = ${JSON.stringify(manifest, null, 2)} as const satisfies Record<\n` +
    `  'blue' | 'brown' | 'red' | 'cream',\n` +
    `  { down: readonly (readonly [number, number])[]; up: readonly (readonly [number, number])[] }\n` +
    `>;\n`,
);
